name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - v4.1

jobs:
  buildtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rcmcarddav
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v5
    - name: Run unit tests
      uses: php-actions/phpunit@v2
      with:
        configuration: tests/unit/phpunit.xml
