name: CI Build

on:
    workflow_dispatch:
    push:
        branches:
            - v4.1

jobs:
  buildtest:
    runs-on: ubuntu-latest

    env:
        XDEBUG_MODE: coverage

    steps:
    - name: Checkout rcmcarddav
      uses: actions/checkout@v2
    - name: Checkout roundcubemail
      uses: actions/checkout@v2
      with:
        path: roundcubemail
        repository: roundcube/roundcubemail
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: '7.4'
        args: --ignore-platform-reqs
    - name: Run unit tests
      uses: php-actions/phpunit@v2
      with:
        configuration: tests/unit/phpunit.xml
        php_version: '7.4'
        php_extensions: xdebug gd
    - name: Upload coverage reports to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: testreports/coverage-unit-clover.xml
        flags: unittests
        name: RCMCardDAV test coverage
        fail_ci_if_error: false
