name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - v4.1

jobs:
  buildtest:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP extensions
      uses: shivammathur/setup-php@v2
      with:
        php_version: '7.4'
        extensions: gd
        coverage: xdebug
    - name: Checkout rcmcarddav
      uses: actions/checkout@v2
    - name: Checkout roundcubemail
      uses: actions/checkout@v2
      with:
        path: roundcubemail
        repository: roundcube/roundcubemail
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: '7.4'
    - name: Run unit tests
      uses: php-actions/phpunit@v2
      with:
        configuration: tests/unit/phpunit.xml
        php_version: '7.4'
